### PR TITLE
bump Texture to 1.0

### PR DESCRIPTION
**Pull request by axfelix**

### CODE REVIEW

**Comment by asmecher** [comment]
@axfelix, is this tested? Also, could you describe/document the build process?

**Comment by axfelix** [comment]
It appears to be throwing `Uncaught TypeError: substance.HttpStorageClient is not a constructor`.

How did you build this standalone plugin in the first place?

I had a process for rebuilding the old plugin from texture upstream; my workflow was to clone texture locally -> `npm install` -> `npm run release` -> replace any updated .js or .css files from `/dist` into our plugin

**Comment by asmecher** [comment]
I'm pretty sure those are just the files from Kassim's `ojs3-markup` plugin, minus the OTS part of it. I didn't rebuild Texture.

**Comment by axfelix** [comment]
Well, I built texture to generate those in the first place, so 🙃

**Comment by axfelix** [comment]
And I've just tested and your plugin repo seems to be throwing the same error too, with the version of Texture you originally built it with. Did you test it at any point? I'm afraid you might've broken something from Kassim's plugin...

**Comment by asmecher** [comment]
Is it possible that the document you're using is making Texture unhappy? I've been testing it with the document that's included in the repo.

**Comment by axfelix** [comment]
I've just tested it again and it appears to work fine (both the version you originally built the plugin with and my branch with 1.0)... very likely I'm failing to understand OJS plugin version caching again. Sorry for the confusion; I think this can be merged.

**Comment by asmecher** [comment]
Now I'm getting `Uncaught TypeError: substance.HttpStorageClient is not a constructor` too -- but only on your branch, not on `origin/master`.

**Comment by asmecher** [comment]
(This seems to be related to https://github.com/substance/texture/issues/457.)

**Comment by axfelix** [comment]
Yeah, we worked the manifest requirement into the other plugin before this was split out, I'm just still not clear on why anything would be different from the last build. I've asked them if anything changed in the backend and am waiting to hear back, but I believe the answer is no...

**Comment by asmecher** [comment]
The initial error is because some classes have moved namespaces -- e.g. references to `substance.HttpStorageClient` need to be changed to `texture.HttpStorageClient` in `editor.js`. But that's not sufficient to get it working.

**Comment by asmecher** [comment]
(A pull to resolve the namespace change: https://github.com/axfelix/texture/pull/1)

**Comment by asmecher** [comment]
With the above PR merged, it gets a little closer...

error

**Comment by axfelix** [comment]
I still think we're missing something here -- very little should've changed from the last beta and the last wrapper was working...

**Comment by asmecher** [comment]
Previously we were using preview2 (https://github.com/kaschioudi/ojs3-markup/commit/42d20e6fc7532558ff9e3b4f1ff35f22900f4d4e), so I guess we skipped over preview2.1, and the diff from `v1.0.0-preview.2` to `v1.0` looks considerable to me.

**Pull request closed without merging**
